# Merging the CPI and PCPS dataframes

# Contents
Importing libraries<br>
Resetting pandas column and row display options to maximum<br>
Defining path variable<br>
Importing cleaned dataframes<br>
Merging the dataframes<br>
- Merging the cpi elements and pcps dataframes
- Merging the overall cpi and pcps dataframes
- Renaming the merge flag column 
- Checking the merged dataframes
    - Checking the cpi elements merged dataframe
    - Checking the overall cpi merged dataframe

Exporting the merged dataframes<br>

## Importing libraries

In [1]:
# importing libraries
import pandas as pd
import numpy as np
import os

## Resetting pandas column and row display options to maximum

In [2]:
# resetting pandas row and column display options to maximum
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## Defining path variable

In [3]:
# defining path variable
path = r"C:\Users\khand\Desktop\Careerfoundry\Data Immersion\Achievement - 6\Project - IMF Data Analysis"

## Importing the cleaned dataframes

In [4]:
# importing cpi cleaned dataframe
df_cpi = pd.read_csv(os.path.join(path, '2. Data', 'Prepared Data', 'cpi_data_cleaned_columns_re_arranged_csv.csv'), index_col = False)

In [5]:
# importing the overall cpi datafrane
df_overall_cpi = pd.read_csv(os.path.join(path, '2. Data', 'Prepared Data', 'overall_cpi_csv.csv'), index_col = False)

In [6]:
# importing pcps cleaned dataframe
df_pcps = pd.read_csv(os.path.join(path, '2. Data', 'Prepared Data', 'pcps_data_clean_csv.csv'), index_col = False)

In [7]:
# checking the cpi dataframe
df_cpi.head()

,country_name,month_code,year,month_number,month,alcoholic_beverages_tobacco_narcotics,alcoholic_beverages_tobacco_narcotics_weight_percent,clothing_footwear,clothing_footwear_weight_percent,communication,communication_weight_percent,consumer_price_index_all_items,education,education_weight_percent,food_non-alcoholic_beverages,food_non-alcoholic_beverages_weight_percent,furnishings_household_equipment_routine_household_maintenance,furnishings_household_equipment_routine_household_maintenance_weight_percent,health,health_weight_percent,housing_water_electricity_gas_other_fuels,housing_water_electricity_gas_other_fuels_weight_percent,miscellaneous_goods_services,miscellaneous_goods_services_weight_percent,recreation_culture,recreation_culture_weight_percent,restaurants_hotels,restaurants_hotels_weight_percent,transport,transport_weight_percent
0,Albania,2010M1,2010,1,January,68.283576,6.425297,114.819974,10.804245,97.001081,9.127536,82.366797,81.545333,7.673192,72.823960,6.852535,94.834432,8.923660,91.855580,8.643358,87.480054,8.231633,83.800015,7.885352,88.614960,8.338425,88.408993,8.319044,93.262240,8.775721
1,Albania,2010M10,2010,10,October,71.053034,6.567009,112.831495,10.428343,97.608435,9.021366,82.890201,81.094181,7.495052,71.587691,6.616424,94.876880,8.768905,103.589187,9.574132,90.568215,8.370681,85.340222,7.887489,88.950901,8.221202,89.399429,8.262657,95.069851,8.786740
2,Albania,2010M11,2010,11,November,70.955607,6.553246,112.999217,10.436268,97.608435,9.014821,83.043531,81.103472,7.490473,71.800099,6.631241,94.950721,8.769363,103.589187,9.567186,90.832398,8.389007,85.350017,7.882671,89.015308,8.221186,89.439571,8.260370,95.111026,8.784168
3,Albania,2010M12,2010,12,December,72.320272,6.636115,113.137816,10.381537,97.608435,8.956559,84.863082,81.103877,7.442099,75.128872,6.893832,95.075429,8.724130,103.595974,9.505976,91.595634,8.404824,85.394290,7.835788,88.982177,8.165013,89.532851,8.215543,96.322736,8.838583
4,Albania,2010M2,2010,2,February,68.466207,6.408273,114.298352,10.698051,96.995412,9.078538,83.623075,81.557395,7.633576,74.577762,6.980299,94.938916,8.886054,92.039008,8.614630,89.781999,8.403379,85.142420,7.969126,88.513123,8.284616,88.569319,8.289875,93.523581,8.753582

In [8]:
# checking column names, data types, value counts, number of rows and columns
df_cpi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16128 entries, 0 to 16127
Data columns (total 30 columns):
 #   Column                                                                        Non-Null Count  Dtype
---  ------                                                                        --------------  -----
 0   country_name                                                                  16128 non-null  object
 1   month_code                                                                    16128 non-null  object
 2   year                                                                          16128 non-null  int64
 3   month_number                                                                  16128 non-null  int64
 4   month                                                                         16128 non-null  object
 5   alcoholic_beverages_tobacco_narcotics                                         16128 non-null  float64
 6   alcoholic_beverages_tobacco_narcotics_weight_percent                          16128 non-null  float64
 7   clothing_footwear                                                             16128 non-null  float64
 8   clothing_footwear_weight_percent                                              16128 non-null  float64
 9   communication                                                                 16128 non-null  float64
 10  communication_weight_percent                                                  16128 non-null  float64
 11  consumer_price_index_all_items                                                16128 non-null  float64
 12  education                                                                     16128 non-null  float64
 13  education_weight_percent                                                      16128 non-null  float64
 14  food_non-alcoholic_beverages                                                  16128 non-null  float64
 15  food_non-alcoholic_beverages_weight_percent                                   16128 non-null  float64
 16  furnishings_household_equipment_routine_household_maintenance                 16128 non-null  float64
 17  furnishings_household_equipment_routine_household_maintenance_weight_percent  16128 non-null  float64
 18  health                                                                        16128 non-null  float64
 19  health_weight_percent                                                         16128 non-null  float64
 20  housing_water_electricity_gas_other_fuels                                     16128 non-null  float64
 21  housing_water_electricity_gas_other_fuels_weight_percent                      16128 non-null  float64
 22  miscellaneous_goods_services                                                  16128 non-null  float64
 23  miscellaneous_goods_services_weight_percent                                   16128 non-null  float64
 24  recreation_culture                                                            16128 non-null  float64
 25  recreation_culture_weight_percent                                             16128 non-null  float64
 26  restaurants_hotels                                                            16128 non-null  float64
 27  restaurants_hotels_weight_percent                                             16128 non-null  float64
 28  transport                                                                     16128 non-null  float64
 29  transport_weight_percent                                                      16128 non-null  float64
dtypes: float64(25), int64(2), object(3)
memory usage: 3.7+ MB

In [9]:
# checking the pcps dataframe
df_pcps.head()

,month_code,agr_raw_material_index,agriculture,all_index,all_metals_ex_gold_index,all_metals_index,apsp_crude_oil_us_dollar_per_bbl,beverages_index,coal_index,commodities_for_index_all_excluding_gold,energy_index,fertilizer,food_and_beverage_index,food_index,industrial_materials_index,metal_index,natural_gas_index,non_fuel_index,precious_metals_price_index
0,2003M1,75.818524,66.404642,65.339345,44.273201,37.259978,72.887892,53.490734,40.347582,69.497192,80.490252,56.035391,65.013030,65.987927,53.440527,44.545787,119.610081,54.864976,30.216031
1,2003M10,83.039186,73.914567,67.454703,51.043815,41.793628,65.680893,45.077185,49.497189,71.651938,76.389471,65.009596,72.565716,74.891508,60.763881,51.909958,111.137063,61.277774,32.013124
2,2003M11,83.453041,72.069320,67.381915,53.611330,43.606859,65.810034,44.858141,53.281767,71.471315,76.609654,68.231997,70.386516,72.546460,62.838932,54.645296,110.265222,61.002445,32.934858
3,2003M12,81.470136,71.443686,70.506308,57.987087,46.636649,66.156400,47.158730,56.018218,74.794724,83.000744,70.281467,69.961522,71.890856,65.546859,59.217722,132.265446,61.868453,34.473222
4,2003M2,76.401557,66.761576,70.345482,45.632841,38.087343,77.812541,54.513241,40.375689,75.050545,91.762030,60.633240,65.336541,66.252296,54.590586,45.921225,153.068330,55.539449,30.513517

In [10]:
# checking column names, data types, value counts, number of rows and columns in the pcps dataframe
df_pcps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 19 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   month_code                                233 non-null    object
 1   agr_raw_material_index                    233 non-null    float64
 2   agriculture                               233 non-null    float64
 3   all_index                                 233 non-null    float64
 4   all_metals_ex_gold_index                  233 non-null    float64
 5   all_metals_index                          233 non-null    float64
 6   apsp_crude_oil_us_dollar_per_bbl          233 non-null    float64
 7   beverages_index                           233 non-null    float64
 8   coal_index                                233 non-null    float64
 9   commodities_for_index_all_excluding_gold  233 non-null    float64
 10  energy_index                              233 non-null    float64
 11  fertilizer                                233 non-null    float64
 12  food_and_beverage_index                   233 non-null    float64
 13  food_index                                233 non-null    float64
 14  industrial_materials_index                233 non-null    float64
 15  metal_index                               233 non-null    float64
 16  natural_gas_index                         233 non-null    float64
 17  non_fuel_index                            233 non-null    float64
 18  precious_metals_price_index               233 non-null    float64
dtypes: float64(18), object(1)
memory usage: 34.7+ KB

In [11]:
# checking the cpi overall dataframe
df_overall_cpi.head()

  country_name month_code  year  month_number  consumer_price_index_all_items
0      Albania     2010M1  2010             1                       82.366797
1      Albania     2010M2  2010             2                       83.623075
2      Albania     2010M3  2010             3                       83.691822
3      Albania     2010M4  2010             4                       83.321715
4      Albania     2010M5  2010             5                       83.691822

In [12]:
# checking column names, data types, value counts, number of rows and columns in the overall cpi dataframe
df_overall_cpi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22752 entries, 0 to 22751
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   country_name                    22752 non-null  object
 1   month_code                      22752 non-null  object
 2   year                            22752 non-null  int64
 3   month_number                    22752 non-null  int64
 4   consumer_price_index_all_items  22752 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 888.9+ KB

## Merging the dataframes

### Merging the CPI elements and PCPS dataframe

In [13]:
# merging the cpi and pcps dataframe
df_cpi_elements_pcps_merged = df_cpi.merge(df_pcps, on = ['month_code'], how = 'left', indicator = True )

In [14]:
# checking the column names, data types, nuber of rows and columns in the merged dataframe
df_cpi_elements_pcps_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16128 entries, 0 to 16127
Data columns (total 49 columns):
 #   Column                                                                        Non-Null Count  Dtype
---  ------                                                                        --------------  -----
 0   country_name                                                                  16128 non-null  object
 1   month_code                                                                    16128 non-null  object
 2   year                                                                          16128 non-null  int64
 3   month_number                                                                  16128 non-null  int64
 4   month                                                                         16128 non-null  object
 5   alcoholic_beverages_tobacco_narcotics                                         16128 non-null  float64
 6   alcoholic_beverages_tobacco_narcotics_weight_percent                          16128 non-null  float64
 7   clothing_footwear                                                             16128 non-null  float64
 8   clothing_footwear_weight_percent                                              16128 non-null  float64
 9   communication                                                                 16128 non-null  float64
 10  communication_weight_percent                                                  16128 non-null  float64
 11  consumer_price_index_all_items                                                16128 non-null  float64
 12  education                                                                     16128 non-null  float64
 13  education_weight_percent                                                      16128 non-null  float64
 14  food_non-alcoholic_beverages                                                  16128 non-null  float64
 15  food_non-alcoholic_beverages_weight_percent                                   16128 non-null  float64
 16  furnishings_household_equipment_routine_household_maintenance                 16128 non-null  float64
 17  furnishings_household_equipment_routine_household_maintenance_weight_percent  16128 non-null  float64
 18  health                                                                        16128 non-null  float64
 19  health_weight_percent                                                         16128 non-null  float64
 20  housing_water_electricity_gas_other_fuels                                     16128 non-null  float64
 21  housing_water_electricity_gas_other_fuels_weight_percent                      16128 non-null  float64
 22  miscellaneous_goods_services                                                  16128 non-null  float64
 23  miscellaneous_goods_services_weight_percent                                   16128 non-null  float64
 24  recreation_culture                                                            16128 non-null  float64
 25  recreation_culture_weight_percent                                             16128 non-null  float64
 26  restaurants_hotels                                                            16128 non-null  float64
 27  restaurants_hotels_weight_percent                                             16128 non-null  float64
 28  transport                                                                     16128 non-null  float64
 29  transport_weight_percent                                                      16128 non-null  float64
 30  agr_raw_material_index                                                        16128 non-null  float64
 31  agriculture                                                                   16128 non-null  float64
 32  all_index                                                                     16128 non-null  float64
 33  all_metals_ex_gold_index                                                      16128 non-null  float64
 34  all_metals_index                                                              16128 non-null  float64
 35  apsp_crude_oil_us_dollar_per_bbl                                              16128 non-null  float64
 36  beverages_index                                                               16128 non-null  float64
 37  coal_index                                                                    16128 non-null  float64
 38  commodities_for_index_all_excluding_gold                                      16128 non-null  float64
 39  energy_index                                                                  16128 non-null  float64
 40  fertilizer                                                                    16128 non-null  float64
 41  food_and_beverage_index                                                       16128 non-null  float64
 42  food_index                                                                    16128 non-null  float64
 43  industrial_materials_index                                                    16128 non-null  float64
 44  metal_index                                                                   16128 non-null  float64
 45  natural_gas_index                                                             16128 non-null  float64
 46  non_fuel_index                                                                16128 non-null  float64
 47  precious_metals_price_index                                                   16128 non-null  float64
 48  _merge                                                                        16128 non-null  category
dtypes: category(1), float64(43), int64(2), object(3)
memory usage: 6.0+ MB

### Checking and Removing the merge flag column

In [15]:
# checking the value of the merge column
df_cpi_elements_pcps_merged['_merge'].value_counts(dropna = False)

both          16128
left_only         0
right_only        0
Name: _merge, dtype: int64

In [18]:
# dropping the '_merge' column
df_cpi_elements_pcps_merged.drop('_merge', axis = 1, inplace = True)
df_cpi_elements_pcps_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16128 entries, 0 to 16127
Data columns (total 48 columns):
 #   Column                                                                        Non-Null Count  Dtype
---  ------                                                                        --------------  -----
 0   country_name                                                                  16128 non-null  object
 1   month_code                                                                    16128 non-null  object
 2   year                                                                          16128 non-null  int64
 3   month_number                                                                  16128 non-null  int64
 4   month                                                                         16128 non-null  object
 5   alcoholic_beverages_tobacco_narcotics                                         16128 non-null  float64
 6   alcoholic_beverages_tobacco_narcotics_weight_percent                          16128 non-null  float64
 7   clothing_footwear                                                             16128 non-null  float64
 8   clothing_footwear_weight_percent                                              16128 non-null  float64
 9   communication                                                                 16128 non-null  float64
 10  communication_weight_percent                                                  16128 non-null  float64
 11  consumer_price_index_all_items                                                16128 non-null  float64
 12  education                                                                     16128 non-null  float64
 13  education_weight_percent                                                      16128 non-null  float64
 14  food_non-alcoholic_beverages                                                  16128 non-null  float64
 15  food_non-alcoholic_beverages_weight_percent                                   16128 non-null  float64
 16  furnishings_household_equipment_routine_household_maintenance                 16128 non-null  float64
 17  furnishings_household_equipment_routine_household_maintenance_weight_percent  16128 non-null  float64
 18  health                                                                        16128 non-null  float64
 19  health_weight_percent                                                         16128 non-null  float64
 20  housing_water_electricity_gas_other_fuels                                     16128 non-null  float64
 21  housing_water_electricity_gas_other_fuels_weight_percent                      16128 non-null  float64
 22  miscellaneous_goods_services                                                  16128 non-null  float64
 23  miscellaneous_goods_services_weight_percent                                   16128 non-null  float64
 24  recreation_culture                                                            16128 non-null  float64
 25  recreation_culture_weight_percent                                             16128 non-null  float64
 26  restaurants_hotels                                                            16128 non-null  float64
 27  restaurants_hotels_weight_percent                                             16128 non-null  float64
 28  transport                                                                     16128 non-null  float64
 29  transport_weight_percent                                                      16128 non-null  float64
 30  agr_raw_material_index                                                        16128 non-null  float64
 31  agriculture                                                                   16128 non-null  float64
 32  all_index                                                                     16128 non-null  float64
 33  all_metals_ex_gold_index                                                      16128 non-null  float64
 34  all_metals_index                                                              16128 non-null  float64
 35  apsp_crude_oil_us_dollar_per_bbl                                              16128 non-null  float64
 36  beverages_index                                                               16128 non-null  float64
 37  coal_index                                                                    16128 non-null  float64
 38  commodities_for_index_all_excluding_gold                                      16128 non-null  float64
 39  energy_index                                                                  16128 non-null  float64
 40  fertilizer                                                                    16128 non-null  float64
 41  food_and_beverage_index                                                       16128 non-null  float64
 42  food_index                                                                    16128 non-null  float64
 43  industrial_materials_index                                                    16128 non-null  float64
 44  metal_index                                                                   16128 non-null  float64
 45  natural_gas_index                                                             16128 non-null  float64
 46  non_fuel_index                                                                16128 non-null  float64
 47  precious_metals_price_index                                                   16128 non-null  float64
dtypes: float64(43), int64(2), object(3)
memory usage: 6.0+ MB

### Merging the overall CPI dataframe and PCPS dataframe

In [19]:
df_overall_cpi_pcps_merged = df_overall_cpi.merge(df_pcps, on = ['month_code'], how = 'left', indicator = True)
df_overall_cpi_pcps_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22752 entries, 0 to 22751
Data columns (total 24 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   country_name                              22752 non-null  object
 1   month_code                                22752 non-null  object
 2   year                                      22752 non-null  int64
 3   month_number                              22752 non-null  int64
 4   consumer_price_index_all_items            22752 non-null  float64
 5   agr_raw_material_index                    22752 non-null  float64
 6   agriculture                               22752 non-null  float64
 7   all_index                                 22752 non-null  float64
 8   all_metals_ex_gold_index                  22752 non-null  float64
 9   all_metals_index                          22752 non-null  float64
 10  apsp_crude_oil_us_dollar_per_bbl          22752 non-null  float64
 11  beverages_index                           22752 non-null  float64
 12  coal_index                                22752 non-null  float64
 13  commodities_for_index_all_excluding_gold  22752 non-null  float64
 14  energy_index                              22752 non-null  float64
 15  fertilizer                                22752 non-null  float64
 16  food_and_beverage_index                   22752 non-null  float64
 17  food_index                                22752 non-null  float64
 18  industrial_materials_index                22752 non-null  float64
 19  metal_index                               22752 non-null  float64
 20  natural_gas_index                         22752 non-null  float64
 21  non_fuel_index                            22752 non-null  float64
 22  precious_metals_price_index               22752 non-null  float64
 23  _merge                                    22752 non-null  category
dtypes: category(1), float64(19), int64(2), object(2)
memory usage: 4.2+ MB

### Checking and removing the merge column

In [20]:
# checking the merge column
df_overall_cpi_pcps_merged['_merge'].value_counts(dropna = False)

both          22752
left_only         0
right_only        0
Name: _merge, dtype: int64

In [21]:
# removing the merge column
df_overall_cpi_pcps_merged.drop('_merge', axis = 1, inplace = True)
df_overall_cpi_pcps_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22752 entries, 0 to 22751
Data columns (total 23 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   country_name                              22752 non-null  object
 1   month_code                                22752 non-null  object
 2   year                                      22752 non-null  int64
 3   month_number                              22752 non-null  int64
 4   consumer_price_index_all_items            22752 non-null  float64
 5   agr_raw_material_index                    22752 non-null  float64
 6   agriculture                               22752 non-null  float64
 7   all_index                                 22752 non-null  float64
 8   all_metals_ex_gold_index                  22752 non-null  float64
 9   all_metals_index                          22752 non-null  float64
 10  apsp_crude_oil_us_dollar_per_bbl          22752 non-null  float64
 11  beverages_index                           22752 non-null  float64
 12  coal_index                                22752 non-null  float64
 13  commodities_for_index_all_excluding_gold  22752 non-null  float64
 14  energy_index                              22752 non-null  float64
 15  fertilizer                                22752 non-null  float64
 16  food_and_beverage_index                   22752 non-null  float64
 17  food_index                                22752 non-null  float64
 18  industrial_materials_index                22752 non-null  float64
 19  metal_index                               22752 non-null  float64
 20  natural_gas_index                         22752 non-null  float64
 21  non_fuel_index                            22752 non-null  float64
 22  precious_metals_price_index               22752 non-null  float64
dtypes: float64(19), int64(2), object(2)
memory usage: 4.2+ MB

## Checking the merged dataframes

#### Checking the df_cpi_elements_pcps_merged

In [22]:
# checking the null values in the merged dataframe
df_cpi_elements_pcps_merged.isnull().sum()

country_name                                                                    0
month_code                                                                      0
year                                                                            0
month_number                                                                    0
month                                                                           0
alcoholic_beverages_tobacco_narcotics                                           0
alcoholic_beverages_tobacco_narcotics_weight_percent                            0
clothing_footwear                                                               0
clothing_footwear_weight_percent                                                0
communication                                                                   0
communication_weight_percent                                                    0
consumer_price_index_all_items                                                  0
education                                                                       0
education_weight_percent                                                        0
food_non-alcoholic_beverages                                                    0
food_non-alcoholic_beverages_weight_percent                                     0
furnishings_household_equipment_routine_household_maintenance                   0
furnishings_household_equipment_routine_household_maintenance_weight_percent    0
health                                                                          0
health_weight_percent                                                           0
housing_water_electricity_gas_other_fuels                                       0
housing_water_electricity_gas_other_fuels_weight_percent                        0
miscellaneous_goods_services                                                    0
miscellaneous_goods_services_weight_percent                                     0
recreation_culture                                                              0
recreation_culture_weight_percent                                               0
restaurants_hotels                                                              0
restaurants_hotels_weight_percent                                               0
transport                                                                       0
transport_weight_percent                                                        0
agr_raw_material_index                                                          0
agriculture                                                                     0
all_index                                                                       0
all_metals_ex_gold_index                                                        0
all_metals_index                                                                0
apsp_crude_oil_us_dollar_per_bbl                                                0
beverages_index                                                                 0
coal_index                                                                      0
commodities_for_index_all_excluding_gold                                        0
energy_index                                                                    0
fertilizer                                                                      0
food_and_beverage_index                                                         0
food_index                                                                      0
industrial_materials_index                                                      0
metal_index                                                                     0
natural_gas_index                                                               0
non_fuel_index                                                                  0
precious_metals_price_index                                                     0
dtype: int64

In [24]:
# checking for duplicates
df_cpi_elements_pcps_merged.duplicated().sum()

0

#### Checkign the df_overall_cpi_pcps_merged dataframe

In [25]:
# checking for misssing values
df_overall_cpi_pcps_merged.isnull().sum()

country_name                                0
month_code                                  0
year                                        0
month_number                                0
consumer_price_index_all_items              0
agr_raw_material_index                      0
agriculture                                 0
all_index                                   0
all_metals_ex_gold_index                    0
all_metals_index                            0
apsp_crude_oil_us_dollar_per_bbl            0
beverages_index                             0
coal_index                                  0
commodities_for_index_all_excluding_gold    0
energy_index                                0
fertilizer                                  0
food_and_beverage_index                     0
food_index                                  0
industrial_materials_index                  0
metal_index                                 0
natural_gas_index                           0
non_fuel_index                              0
precious_metals_price_index                 0
dtype: int64

In [26]:
# checking for duplicates
df_overall_cpi_pcps_merged.duplicated().sum()

0

## Exporting the merged dataframes

In [28]:
# exporting the merged dataframes
df_cpi_elements_pcps_merged.to_csv(os.path.join(path, '2. Data', 'Prepared Data', 'cpi_elements_pcps_merged_csv.csv'), index = None)
df_cpi_elements_pcps_merged.to_pickle(os.path.join(path, '2. Data', 'Prepared Data', 'cpi_elements_pcps_merged_pickle.pkl'))
df_overall_cpi_pcps_merged.to_csv(os.path.join(path, '2. Data', 'Prepared Data', 'overall_cpi_pcps_merged_csv.csv'), index = None)
df_overall_cpi_pcps_merged.to_pickle(os.path.join(path, '2. Data', 'Prepared Data', 'overall_cpi_pcps_merged_pkl.pkl'))